services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sauravphp
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:1.27.4
    container_name: sauravnginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
